groups:
    - developer
    - media

attributes:
    osxdefaults:
        finder:
            finder_set_preferred_view_style: Nlsv
        terminal:
            profile: Solarized-Dark-ansi
        computername: silence

    git:
        name: Johan Lindblom
        email: lindblom.j@gmail.com
    authorization:
        sudo:
            users:
                - johanl
            passwordless: true
            include_sudoers_d: true
